# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GetSmart' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GetSmart

pod 'IQKeyboardManagerSwift'
pod 'Alamofire'
pod 'MBProgressHUD'
pod 'DropDown'
pod 'SlideMenuControllerSwift'
pod 'Kingfisher'
pod 'OneSignal'
pod 'ReachabilitySwift'
pod 'UICircularProgressRing'
pod 'ActionSheetPicker'
pod 'GTProgressBar'

end
